### ISSUE TITLE
Question - GIF Creations Instead Of Only Images

### ISSUE THREAD

**Issue by Roebou1989** [nftchef/art-engine#114]
Hi @nftchef ,

I have been searching far and wide, but not getting any direction on this topic. I have a user that would like to be able to use a layer setup where they have both gifs and png files as their layer items, all with transparent backgrounds, apart from the backgrounds folder, and would like to build a new gif that is made up of the combination of these layers.

Have you been able to build this on your side before or have seen anyone one build it or can perhaps assist me in building this out? I am attaching a layer configuration set if you would like to take a stab at it.

[Layer.zip](https://github.com/nftchef/art-engine/files/8255495/Layer.zip)

Thanks for all your work on the code repo, much appreciated!

Kind Regards,
Rohan (ThePeanutGalleryAndCo) ;)

**Comment by nftchef** [comment]
In order to do this you will need some customization to the engine or the input artwork. There is a good example of gif's from sprite sheets in this repo: https://github.com/MichaPipo/Generative_Gif_Engine

To do it with gif's and png's, you will need to add some custom handling features that can auto-create sprite sheets while doing the image generation and compile it all back to a gif in the end.
