### ISSUE TITLE
Altered opacity of layers

### ISSUE THREAD

**Issue by buhduhzah** [nftchef/art-engine#207]
I have a "ghost" skin layer that is supposed to be slightly opaque to the background layer. Running it through this art gen reduces the opacity (and moves it closer to a solid layer).

Any ideas for fixing this?

**Comment by BarryDB83** [comment]
Might be off-topic, but I had a similar problem and the issue wasn't NFT Chef. Try reopening your layers in Photoshop and make sure they are still opaque and you didn't have issues exporting them.

I exported from photoshop using layers to files and made sure I checked 'transparent'. Somehow opaque parts came out solid. I had to export opaque layers one by one instead of batch exporting them.

**Comment by advra** [comment]
This is not related to photoshop or how the image is saved. This is related to the art-engine which renders images twice making your slightly transparent image appear more opaque. The fix is posted at this [PR](https://github.com/nftchef/art-engine/pull/190)

**Comment by nftchef** [comment]
Fixed in #190
